# Worlds that are NOT protected
Endermen:
- unprotectedworld
Sheep:
- unprotectedworld
MobExplosion:
- unprotectedworld
TNT:
- unprotectedworld
Snowman:
- unprotectedworld
Silverfish:
- unprotectedworld